### ISSUE TITLE
chore: find examples of OSS monorepos

### ISSUE THREAD

**Issue by Stealthmate** [Stealthmate/wakate#3]

**Comment by Stealthmate** [comment]
09/04 09:00 まで
ここに列挙してくれればOK

**Comment by tamofplease** [comment]
[Babel](https://github.com/babel/babel)

- packages, codemods(簡単なscript), docsなど
- パッケージのバージョン管理には[lerna](https://github.com/lerna/lerna)を利用
- 単一言語(ほぼほぼJS)

#### 一言

`lerna`初めて知った。pnpm workspace, yarn workspace的な感じでnpmに対して使えるものと理解した。(結局こういうまとめる系のツールを使ってるケースが多いのかね)

---------------

[React](https://github.com/facebook/react)

- React本体、React DOM、テストユーティリティ
- packages/ディレクトリ内に各Reactパッケージ、そのほかfixtures/、scripts/などの補助ディレクトリがある
- JS, TS, rust(for compiler), C++for react native)

#### 一言

利用言語の構成はJS(ベース), TS(型定義提供)+ rust, c++考えると、必要に応じて都度最適な言語選定しているというよりかは他に選択肢がなさそう。(web applicationとは大きく違う)

---------------

[Yarn](https://github.com/yarnpkg/yarn)

- Yarnのコア、CLIツール、プラグイン
- packages/にそれぞれのYarnパッケージ + scripts/、__tests__/
- JSに統一されてそう



#### 一言

yarnのtest実行にはyarnを利用している。

perplexity曰く、`Workspacesを使用して内部依存関係を管理`らしいけそそんな痕跡はなかった(本当だったら面白いのに...)


---------------

[NixOS](https://github.com/NixOS/nixpkgs)


- パッケージ定義(めっちゃ多い)とシステム設定
- pkgs/ディレクトリ内に各パッケージの定義ファイルが配置、nixos/ディレクトリにNixOSの設定ファイル
- 主にNix言語で書かれている

#### 一言

他Projectと違ってだいぶ異質かも...てかそもそもこのあたりになるとそもそもrepo分けるという選択の余地はなさそう...?

---------------

[ProtonMail](https://github.com/ProtonMail/WebClients)

- ProtonMail、ProtonCalendar、ProtonContactsなどのWebクライアント
- Yarn workspacesを使用して内部依存関係を管理
- applications/ディレクトリ内に各Webクライアントのコードが配置 & packages/ディレクトリに共有コンポーネントやユーティリティが配置
- ほぼTS


#### 一言

WebClientだけでmonorepo構成しているのおもろい。(しかも異なるapplicationの...ってところ)


---------------

**Comment by tamofplease** [comment]
とりあえず5つ(追加で必要なら別途対応する)
