### ISSUE TITLE
chore: list people's opinions about monorepos

### ISSUE THREAD

**Issue by Stealthmate** [Stealthmate/wakate#7]

**Comment by tamofplease** [comment]
https://circleci.com/ja/blog/monorepo-dev-practices/

> 共通のコードを変更すると、数多くのアプリケーション コンポーネントに影響が及んでしまいます。ソースの競合によりマージしにくい場合もあります。 
> デプロイ プロセスが複雑化する可能性があり、ソース管理システムのスケーリングも必要です。

**Comment by tamofplease** [comment]
https://tech.buysell-technologies.com/entry/adventcalendar2023-12-11

> 1つの巨大なGitリポジトリを作成する事により、Gitのパフォーマンス低下が起きる可能性があります。

**Comment by tamofplease** [comment]
https://buildersbox.corp-sansan.com/entry/2024/05/27/110000

> チーム構造がフラットでない場合（業務委託など）の権限管理が大変。

**Comment by tamofplease** [comment]
https://kk-web.link/blog/20210507

> 自分が関わらないコードも自分の環境下に置くこととなる
自分に関係のないコミットが打たれる
パッケージ間の依存関係が大量に発生する
関わるメンバー全員にモノレポの知識が求められる

**Comment by tamofplease** [comment]
https://medium.com/streamdal/mostly-terrible-the-monorepo-5db704f76bdb

> If you want to report a bug and you don’t know if it’s caused by the server, wasm , console, or some other component, >where do you submit the issue?
How do folks contribute?

**Comment by Stealthmate** [comment]
メリットは直接コードに入れた． ref: 550530942120b19bb2dd3f4a59b566c5f7b7cfe5
